# Set up HASS
homeassistant: !include hass.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Discover some devices automatically
discovery:

# Allow automatic updates
#updater:

# Enable mobile integrations
mobile_app:

# Write to the log
logger: !include logging.yaml

# Start frontend
frontend: !include frontend.yaml

# Set up web settings (HTTPS, etc.)
http: !include web-http.yaml

# Track devices
device_tracker: !include device_tracker.yaml

# Allow extracting video/audio from websites
media_extractor:

# Give shopping list
shopping_list:

# Notify about breaking changes
#breaking_changes:

#hacs:
#  token: !secret hacs_token

# Set up groups
group: !include groups.yaml

# Set up automations
automation: !include automations.yaml

# Set up scripts
script: !include scripts.yaml
# Give the ability to run Python
python_script:

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token
    
ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring

camera:
  - platform: ring

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: ring
  - platform: template
    sensors:
      bedroom_chromecast_on: 
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Chromecast')}}"
      bedroom_videogames_on: 
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Videogames')}}"
  - platform: nextbus
    agency: lametro-rail
    route: "804"
    stop: "80409_0"
    name: "Union Station to Memorial Park"
  - platform: nextbus
    agency: lametro-rail
    route: "804"
    stop: "80418_1"
    name: "Memorial Park to Union Station"
#  - platform: rpi_power
#    text_state: true
  - platform: plex_recently_added
    token: !secret plex_token
    host: localhost
    port: 32400
    max: 5

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

input_boolean:
  is_jay_bedtime:
    name: Time for Jay to go to bed
    initial: off
    icon: mdi:alarm

input_select:
 remote:
   name: Bedroom Remote
   options:
     - Power Off
     - Watch Chromecast
     - Play Nintendo Switch

notify:
 - platform: html5
   name: push_hass
   vapid_pub_key: BKSMp9OUhOjvSQhwJTAhzsLkbmUsH0i4PO_yjutBUmX1uCOcJDhP2SfaigSJYeSVeCSjVxEkij3dUnBRPvDfIxM
   vapid_prv_key: !secret vapid_prv_key
   vapid_email: !secret jay_email

google:
 client_id: !secret google_client_id
 client_secret: !secret google_client_secret
        
googlehome:
 devices:
   - host: 192.168.86.24
     track_alarms: true
     track_devices: true
   - host: 192.168.86.25
     track_alarms: true
     track_devices: true
   - host: 192.168.86.26
     track_alarms: true
     track_devices: true

# Text to speech
tts:
  - platform: google_translate

hue:
 bridges:
   - host: 192.168.86.21
     allow_unreachable: true
     allow_hue_groups: true

wemo:
 discovery: true
 static:
   - 192.168.86.232
   - 192.168.86.233

#switch:
#  platform: hadockermon
#  host: localhost

#grocy:
#  url: http://localhost:9283/api/
#  api_key: !secret grocy_api
#  sensor:
#    - enabled: true
