alias: "Living Room Stop Playing"
trigger:
- entity_id: media_player.living_room_tv
  platform: state
  from: 'playing'
  to: 'idle'
  for:
    seconds: 15
- entity_id: media_player.living_room_tv
  platform: state
  from: 'playing'
  to: 'off'
- entity_id: media_player.living_room_tv
  platform: state
  from: 'playing'
  to: 'paused'
condition: []
action:
- event: on_living_room_tv_playback_stop
  event_data: {}