alias: "Living Room Stop Playing"
trigger:
- entity_id: media_player.living_room_tv
  platform: state
  from: 'playing'
condition: []
action:
- event: on_living_room_tv_playback_stop
  event_data: {}