add_item:
  description: Adds an item to the shopping inventory.
  fields:
    name: {description: The name of the item to add., example: Beer}
complete_item:
  description: Marks an item as completed in the shopping inventory. It does not remove
    the item.
  fields:
    name: {description: The name of the item to mark as completed., example: Beer}
