alias: Dim Bedroom Lights on Media Start
trigger:
- event_data: {}
  event_type: on_bedroom_tv_playback_start
  platform: event
action:
- condition: state
  entity_id: light.bedroom
  state: "on"
- service: hue.hue_activate_scene
  data:
    group_name: "Bedroom"
    scene_name: "Dimmed"