alias: Turn on fan with temperature rise
trigger:
- event_data: {}
  event_type: office_temperature_rising
  platform: event
condition: []
action:
- service: switch.turn_on
  entity_id: switch.office_fan
