alias: Turn on Chromecast on Awake
trigger:
- event_data: {}
  event_type: jay_woke_up
  platform: event
condition:
  condition: state
  entity_id: sun.sun
  state: 'above_horizon'
action:
- service: remote.turn_on
  entity_id: remote.harmony_hub
  data:
    activity: "Office Chromecast"
