alias: Turn on choo choos
trigger:
  platform: state
  entity_id: input_boolean.choo_choos
  to: 'on'
condition: []
action:
- service: remote.turn_on
  entity_id: remote.harmony_hub
  data:
    activity: "Choo Choos"
- service: switch.turn_on
  entity_id: switch.choo_choos
