alias: Turn off TV when sleeping
trigger:
- event_data: {}
  event_type: start_sleep
  platform: event
condition: []
action:
- service: remote.turn_on
  entity_id: remote.harmony_hub
  data:
    activity: "PowerOff"
