alias: Broadcast when dryer cycle ends
trigger:
- event_data: {}
  event_type: on_dryer_cycle_complete
  platform: event
condition: []
action:
- service: rest_command.assistant_broadcast
  data:
    command: 'Dryer has completed a cycle'
  