alias: Broadcast when dryer has error
trigger:
- event_data: {}
  event_type: on_dryer_error
  platform: event
condition: []
action:
- service: rest_command.assistant_broadcast
  data:
    command: >
      Dryer has encounted an error: {{ state_attr('sensor.dryer', 'error_message') }}
