alias: Broadcast when washer has error
trigger:
- event_data: {}
  event_type: on_washer_error
  platform: event
condition: []
action:
- service: rest_command.assistant_broadcast
  data:
    command: >
      Washer has encounted an error: {{ state_attr('sensor.washer', 'error_message') }}
