alias: Broadcast when washer cycle ends
trigger:
- event_data: {}
  event_type: on_washer_cycle_complete
  platform: event
condition: []
action:
- service: rest_command.assistant_broadcast
  data:
    command: 'Washer has completed a cycle'
