alias: Somebody Home
trigger:
- event_data: {}
  event_type: someone_home
  platform: event
condition: []
action:
- data: {entity_id: all}
  service: switch.turn_on
- data: {entity_id: all}
  service: light.turn_on
