id: '1557988683778'
alias: Fire Michelle Leave Event
trigger:
- entity_id: person.michelle
  for: '15'
  from: home
  platform: state
  to: not_home
condition: []
action:
- event: michelle_leave
  event_data: {}
