alias: Fire Someone Home Event
trigger:
- entity_id: binary_sensor.cutie_home
  platform: state
  to: 'on'
condition: 
- condition: state
  entity_id: binary_sensor.server_up
  state: 'on'
action:
- event: someone_home
  event_data: {}