alias: 'Fire Wake Up Naturally Event'
trigger:
- entity_id: binary_sensor.cuties_asleep
  from: 'on'
  platform: state
  to: 'off'
condition:
  condition: state
  entity_id: sun.sun
  state: 'above_horizon'
action:
- event: woke_up_naturally
  event_data: {}