alias: 'Jay in bed event'
trigger:
- entity_id: binary_sensor.sleep_number_master_bedroom_jay_is_in_bed
  from: 'off'
  platform: state
  to: 'on'
action:
- event: jay_in_bed
  event_data: {}
- service: logbook.log
  data:
    name: Event Fired
    message: Jay in Bed
    domain: automation