id: '1557987182300'
alias: Server Startup
trigger:
- event: start
  platform: homeassistant
condition:
- condition: state
  entity_id: group.household
  state: home
action:
- data:
    message: The server is online!
    entity_id: 'group.broadcast_speakers'
    bug_michelle: False
    push_notification: True
  service: python_script.speak