id: '1559885458753'
alias: Michelle Home Lighting
trigger:
- event_data: {}
  event_type: michelle_home
  platform: event
condition:
- after: sunset
  before: sunrise
  condition: sun
action:
- service: light.turn_on