- id: '1557987182300'
  alias: Server Startup
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - condition: state
    entity_id: input_boolean.is_jay_bedtime
    state: 'off'
  action:
  - data:
      message: The server is online!
    service: notify.push_hass
  - condition: state
    entity_id: person.michelle_kimsey_bailey
    state: not_home
  - data:
      message: The server is online!
    service: script.speak
- id: ifttt_webhook
  alias: Receive IFTTT Webhook
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  action:
  - data_template:
      message: '{{ trigger.event.data.message }}'
    service_template: '{{ trigger.event.data.service }}'
- id: idttt_grocery_added
  alias: IFTTT Added Grocery
  trigger:
  - event_data:
      action: add_grocery
    event_type: ifttt_webhook_received
    platform: event
  action:
  - data_template:
      name: '{{ trigger.event.data.item }}'
    service: shopping_list.add_item
- id: ifttt_webhook_event
  alias: Fire IFTTT Webhook Event
  trigger:
  - event_data:
      action: fire_event
    event_type: ifttt_webhook_received
    platform: event
  action:
  - data_template:
      entity_id: automation.{{ trigger.event.data.event_name }}
    service: automation.trigger
- id: '1557987317420'
  alias: Jay Home Broadcast
  trigger:
  - event_data: {}
    event_type: jay_home
    platform: event
  action:
  - data:
      message: Jay is home!
    service: script.speak
- id: '1557987317421'
  alias: Michelle Home Broadcast
  trigger:
  - event_data: {}
    event_type: michelle_home
    platform: event
  action:
  - data:
      message: Michelle is home!
    service: script.speak
- id: '1557988636756'
  alias: Fire Nobody Home Event
  trigger:
  - event_data: {}
    event_type: jay_leave
    platform: event
  - event_data: {}
    event_type: michelle_leave
    platform: event
  condition:
  - condition: state
    entity_id: group.household
    state: not_home
  action:
  - event: nobody_home
    event_data: {}
- id: '1557988683778'
  alias: Fire Michelle Leave Event
  trigger:
  - entity_id: person.michelle_kimsey_bailey
    for: '15'
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - event: michelle_leave
    event_data: {}
- id: '1557989063218'
  alias: Jay Home Lighting
  trigger:
  - event_data: {}
    event_type: jay_home
    platform: event
  condition:
  - condition: state
    entity_id: person.michelle_kimsey_bailey
    state: not_home
  action:
  - data:
      entity_id: light.office
    service: light.turn_on
- id: '1558072582778'
  alias: Fire Jay Leave Event
  trigger:
  - entity_id: person.jay_stevens
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - event: jay_leave
    event_data: {}
- id: '1558072744651'
  alias: Fire Jay Home Event
  trigger:
  - entity_id: person.jay_stevens
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - event: jay_home
    event_data: {}
- id: '1558072937765'
  alias: Fire Michelle Home Event
  trigger:
  - entity_id: person.michelle_kimsey_bailey
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - event: michelle_home
    event_data: {}
  - data: {}
    service: switch.turn_on
- id: '1558075269028'
  alias: Bedroom Chromecast On
  trigger:
  - entity_id: sensor.bedroom_chromecast_on
    platform: state
    to: 'True'
  condition: []
  action:
  - event: bedroom_chromecast_on
    event_data: {}
- id: '1558075455762'
  alias: Bedroom Videogames On
  trigger:
  - entity_id: sensor.bedroom_videogames_on
    platform: state
    to: 'True'
  condition: []
  action:
  - event: bedroom_videogames_on
    event_data: {}
- id: '1558167145361'
  alias: Jay Bedtime Broadcast
  trigger:
  - entity_id: input_boolean.is_jay_bedtime
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.bedroom_speaker
    state: 'off'
  action:
  - data:
      message: It's time for Jay to go to bed!
    service: script.speak
- id: '1559885458753'
  alias: Michelle Home Lighting
  trigger:
  - event_data: {}
    event_type: michelle_home
    platform: event
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - service: light.turn_on
- id: '1560322936238'
  alias: Fire Doorbell Event
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - event: ring_doorbell
    event_data: {}
- id: '1560323126944'
  alias: Ring Doorbell
  trigger:
  - event_data: {}
    event_type: ring_doorbell
    platform: event
  action:
  - data:
      message: Ding dong! Someone is at the door!
    service: script.speak
- id: '1560485118469'
  alias: Nobody Home
  trigger:
  - event_data: {}
    event_type: nobody_home
    platform: event
  condition: []
  action:
  - data: {}
    service: switch.turn_off
  - data: {}
    service: light.turn_off
  - data: {}
    service: homeassistant.restart
- id: '1560492707401'
  alias: Jay Bedtime
  trigger:
  - event_data: {}
    event_type: jay_bedtime
    platform: event
  condition: []
  action:
  - alias: ''
    data:
      entity_id: input_boolean.is_jay_bedtime
    service: input_boolean.turn_on
- id: '1560492809654'
  alias: Pizza Prepped
  trigger:
  - event_data: {}
    event_type: pizza_prepped
    platform: event
  action:
  - data:
      message: Your pizza order has been received!
    service: script.speak
- id: '1560492989895'
  alias: Pizza Out of Oven
  trigger:
  - event_data: {}
    event_type: pizza_out_of_oven
    platform: event
  action:
  - alias: ''
    data:
      message: Your pizza is out of the oven!
    service: script.speak
- id: '1560493054446'
  alias: Pizza Delivery
  trigger:
  - event_data: {}
    event_type: pizza_delivery
    platform: event
  action:
  - data:
      message: Your pizza is out for delivery!
    service: script.speak
- id: '1560493152641'
  alias: Vitamin Alert
  trigger:
  - event_data: {}
    event_type: vitamin_alert
    platform: event
  action:
  - data:
      message: All cuties should take their vitamins now
    service: script.speak
- id: '1560493801544'
  alias: Jay Alarm
  trigger:
  - event_data: {}
    event_type: jay_alarm
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.is_jay_bedtime
    service: input_boolean.turn_off
- id: '1560638403547'
  alias: Server Startup Nobody Home
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - condition: state
    entity_id: group.household
    state: not_home
  action:
  - data:
      message: The server detected that there's nobody home. If you're hearing this,
        that means Jay fucked up and you should tell him that his shit doesn't work.
        Also, be good, Moo! Baby cat! Little Mooseph!
    service: script.speak
- id: Update Available Notifications
  alias: Update Available Notifications
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data:
      message: Update for Home Assistant is available.
    service: notify.push_hass
- id: '1560661950760'
  alias: Test Working
  trigger:
  - event_data: {}
    event_type: test_working
    platform: event
  condition: []
  action:
  - data:
      entity_id: group.broadcast_speakers
      media_content_id: https://www.youtube.com/watch?v=AXwGVXD7qEQ
      media_content_type: VIDEO
    service: media_extractor.play_media
- id: 'Fire Wake Up Event'
  trigger:
  - entity_id: media_player.bedroom_speaker
    from: 'playing'
    platform: state
    to: 'paused'
  condition:
  - condition: state
    entity_id: person.michelle_kimsey_bailey
    state: not_home
  action:
  - event: morning_greeting
    event_data: {}