alias: Dim Bedroom Lights on Media Start
trigger:
- event_data: {}
  event_type: on_bedroom_tv_playback_start
  platform: event
condition: 
  condition: template
  value_template: "{{ float(states.media_player.bedroom_tv.attributes.media_duration) > 900 }}"
action:
- service: switch.turn_off
  entity_id: switch.bedroom_fan
- condition: state
  entity_id: light.bedroom
  state: "on"
- service: hue.hue_activate_scene
  data:
    group_name: "Bedroom"
    scene_name: "Dimmed"