alias: Bedroom Nobody Home
trigger:
- event_data: {}
  event_type: nobody_home
  platform: event
condition: []
action:
- service: switch.turn_off
  entity_id: switch.bedroom_fan
- service: light.turn_off
  data:
    entity_id: light.bedroom
- service: remote.turn_off
  entity_id: remote.harmony_hub
