alias: Raise bedroom blinds at noon
trigger:
  platform: time
  # Military time format. This trigger will fire at 3:32 PM
  at: "12:00:00"
condition: []
action:
- service: cover.open_cover
  entity_id: cover.bedroom_blind
