id: '1558167145361'
alias: Jay Bedtime Broadcast
trigger:
- entity_id: input_boolean.is_jay_bedtime
  from: 'off'
  platform: state
  to: 'on'
condition:
- condition: state
  entity_id: media_player.bedroom_speaker
  state: 'off'
action:
- data:
    message: It's time for Jay to go to bed!
  service: script.speak