id: 'Jay Leave Work Event'
alias: Fire Jay Leave Work Event
trigger:
- entity_id: person.jay_stevens
  from: Jay Work
  platform: state
  to: not_home
condition:
  condition: time
  after: '16:00:00'
  before: '02:00:00'
action:
- event: jay_leave_work
  event_data: {}
