id: 'Jay Leave Work Event'
alias: Fire Jay Leave Work Event
trigger:
- entity_id: person.jay
  from: Jay Work
  platform: state
  to: not_home
action:
- event: jay_leave_work
  event_data: {}
