id: 'Fire Wake Up Event'
alias: 'Fire Wake Up Event'
trigger:
- entity_id: media_player.bedroom_speaker
  from: 'playing'
  platform: state
  to: 'paused'
condition:
- condition: state
  entity_id: person.michelle_kimsey_bailey
  state: not_home
action:
- event: jay_morning_greeting
  event_data: {}