id: 'Fire Wake Up Event'
alias: 'Fire Wake Up Event'
trigger:
- entity_id: binary_sensor.cuties_asleep
  from: 'on'
  platform: state
  to: 'off'
action:
- event: morning_greeting
  event_data: {}