id: 'Fire Wake Up Event'
alias: 'Fire Wake Up Event'
trigger:
- entity_id: binary_sensor.cuties_asleep
  from: 'on'
  platform: state
  to: 'off'
condition:
- condition: state
  entity_id: person.michelle_kimsey_bailey
  state: not_home
action:
- event: jay_morning_greeting
  event_data: {}