alias: Fire Michelle Home Event
trigger:
- entity_id: person.michelle
  from: not_home
  platform: state
  to: home
condition: 
- condition: state
  entity_id: binary_sensor.server_up
  state: 'on'
action:
- event: michelle_home
  event_data: {}