alias: "Bedroom Stop Playing"
trigger:
- entity_id: media_player.bedroom_tv
  platform: state
  from: 'playing'
  to: 'idle'
  for:
    seconds: 15
- entity_id: media_player.bedroom_tv
  platform: state
  from: 'playing'
  to: 'off'
- entity_id: media_player.bedroom_tv
  platform: state
  from: 'playing'
  to: 'paused'
- entity_id: binary_sensor.bedroom_chromecast_on
  platform: state
  to: 'off'
condition: []
action:
- event: on_bedroom_tv_playback_stop
  event_data: {}