alias: "Bedroom Start Playing"
trigger:
- entity_id: binary_sensor.bedroom_watching_long_media
  platform: state
  to: 'on'
condition: 
  condition: template
  value_template: "{{ not is_state('sensor.bedroom_chromecast_content_type', 'Spotify') }}"
action:
- event: on_bedroom_tv_playback_start
  event_data: {}