alias: Turn off outdoor lights at sunrise
trigger:
- event_data: {}
  event_type: sunrise
  platform: event
condition: []
action:
- service: switch.turn_off
  entity_id: switch.outdoor_lights
- service: switch.turn_off
  entity_id: switch.backyard_lights
