sensor:
  - platform: fitbit
    monitored_resources:
      - "activities/activityCalories"
      - "activities/calories"
      - "activities/distance"
      - "activities/elevation"
      - "activities/heart"
      - "activities/minutesFairlyActive"
      - "activities/minutesLightlyActive"
      - "activities/minutesSedentary"
      - "activities/minutesVeryActive"
      - "activities/steps"
      - "body/bmi"
      - "body/fat"
      - "body/weight"
      - "sleep/awakeningsCount"
      - "sleep/efficiency"
      - "sleep/minutesAfterWakeup"
      - "sleep/minutesAsleep"
      - "sleep/minutesAwake"
      - "sleep/minutesToFallAsleep"
      - "sleep/startTime"
      - "sleep/timeInBed"