binary_sensor:
  - platform: template
    sensors:
      cuties_asleep:
        value_template: >-
          {{ is_state('binary_sensor.white_noise_playing', 'on') }}
      cutie_home:
        value_template: >-
          {{ is_state('person.jay', 'home') 
            or is_state('person.michelle', 'home') }}