# Sensors
sensor:
  # Weather prediction
  - platform: moon
  - platform: time_date
    display_options:
      - 'date_time'
  - platform: uptime
    unit_of_measurement: minutes
  - platform: waqi
    token: !secret air_quality_token
    locations:
      - 'Glendora-Laurel, Los Angeles'
  - platform: template
    sensors:
      outside_temperature:
        value_template: "{{ state_attr('weather.dark_sky', 'temperature') | float }}"
        unit_of_measurement: '°F'
        device_class: temperature
        icon_template: 'mdi:thermometer'
      solar_elevation:
        friendly_name: "Solar Elevation"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        icon_template: 'mdi:weather-sunny'
      solar_azimuth:
        friendly_name: "Azimuth"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
        icon_template: 'mdi:weather-sunny'
      euphrates_eevee_shift_state:
        value_template: "{{ state_attr('binary_sensor.euphrates_eevee_parking_brake_sensor', 'shift_state') }}"
        friendly_name: "Euphrated Eevee Shift State"
        icon_template: 'mdi:car-sports'
      last_time_jay_entered_bed:
        value_template: "{{ as_timestamp(state_attr('automation.jay_in_bed_event', 'last_triggered')) | timestamp_local }}"
        friendly_name: "Last Time Jay Entered Bed"
        icon_template: 'mdi:bed'
        device_class: timestamp
      last_time_jay_left_bed:
        value_template: "{{ as_timestamp(state_attr('automation.jay_left_bed_event', 'last_triggered')) | timestamp_local }}"
        friendly_name: "Last Time Jay Left Bed"
        icon_template: 'mdi:bed'
        device_class: timestamp
      last_time_michelle_entered_bed:
        value_template: "{{ as_timestamp(state_attr('automation.michelle_in_bed_event', 'last_triggered')) | timestamp_local }}"
        friendly_name: "Last Time Michelle Entered Bed"
        device_class: timestamp
      last_time_michelle_left_bed:
        value_template: "{{ as_timestamp(state_attr('automation.michelle_left_bed_event', 'last_triggered')) | timestamp_local }}"
        friendly_name: "Last Time Michelle Left Bed"
        icon_template: 'mdi:bed'
        device_class: timestamp
      seconds_since_jay_entered_bed:
        value_template: >-
          {% if is_state('binary_sensor.sleep_number_master_bedroom_jay_is_in_bed','on') %}
            {{ as_timestamp(now()) - as_timestamp(states('sensor.last_time_jay_entered_bed')) | int }}
          {% else %}
            0
          {% endif %}
        friendly_name: "Seconds Since Jay Entered Bed"
        icon_template: 'mdi:bed'
        entity_id: sensor.date_time
        unit_of_measurement: seconds
      seconds_since_jay_left_bed:
        value_template: >-
          {% if is_state('binary_sensor.sleep_number_master_bedroom_jay_is_in_bed','on') %}
            0
          {% else %}
            {{ as_timestamp(now()) - as_timestamp(states('sensor.last_time_jay_left_bed')) | int }}
          {% endif %}
        friendly_name: "Seconds Since Jay Left Bed"
        icon_template: 'mdi:bed'
        entity_id: sensor.date_time
        unit_of_measurement: seconds
      seconds_since_michelle_entered_bed:
        value_template: >-
          {% if is_state('binary_sensor.sleep_number_master_bedroom_michelle_is_in_bed','on') %}
            {{ as_timestamp(now()) - as_timestamp(states('sensor.last_time_michelle_entered_bed')) | int }}
          {% else %}
            0
          {% endif %}
        friendly_name: "Seconds Since Michelle Entered Bed"
        icon_template: 'mdi:bed'
        entity_id: sensor.date_time
        unit_of_measurement: seconds
      seconds_since_michelle_left_bed:
        value_template: >-
          {% if is_state('binary_sensor.sleep_number_master_bedroom_michelle_is_in_bed','on') %}
            0
          {% else %}
            {{ as_timestamp(now()) - as_timestamp(states('sensor.last_time_michelle_left_bed')) | int }}
          {% endif %}
        friendly_name: "Seconds Since Michelle Left Bed"
        icon_template: 'mdi:bed'
        entity_id: sensor.date_time
        unit_of_measurement: seconds
      minutes_since_jay_entered_bed:
        value_template: "{{ (states('sensor.seconds_since_jay_entered_bed') | float) / 60 }}"
        friendly_name: "Minutes Since Jay Entered Bed"
        icon_template: 'mdi:bed'
        unit_of_measurement: minutes
      minutes_since_jay_left_bed:
        value_template: "{{ (states('sensor.seconds_since_jay_left_bed') | float) / 60 }}"
        friendly_name: "Minutes Since Jay Left Bed"
        icon_template: 'mdi:bed'
        unit_of_measurement: minutes
      minutes_since_michelle_entered_bed:
        value_template: "{{ (states('sensor.seconds_since_michelle_entered_bed') | float) / 60 }}"
        friendly_name: "Minutes Since Michelle Entered Bed"
        icon_template: 'mdi:bed'
        unit_of_measurement: minutes
      minutes_since_michelle_left_bed:
        value_template: "{{ (states('sensor.seconds_since_michelle_left_bed') | float) / 60 }}"
        friendly_name: "Minutes Since Michelle Left Bed"
        icon_template: 'mdi:bed'
        unit_of_measurement: minutes
      jay_game:
        value_template: "{{ state_attr('sensor.discord_englishmobster_2190', 'game') }}"
        friendly_name: "Jay Playing"
        icon_template: 'mdi:gamepad-variant'
      jay_streaming:
        value_template: "{{ state_attr('sensor.discord_englishmobster_2190', 'streaming') }}"
        friendly_name: "Jay Streaming"
        icon_template: 'mdi:twitch'
        attribute_templates:
          jay_streaming_url: "{{ state_attr('sensor.discord_englishmobster_2190', 'streaming_url') }}"
          jay_streaming_details: "{{ state_attr('sensor.discord_englishmobster_2190', 'streaming_details') }}"
      jay_listening:
        value_template: "{{ state_attr('sensor.discord_englishmobster_2190', 'listening') }}"
        friendly_name: "Jay Listening"
        entity_picture_template: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_album_cover_url') }}"
        icon_template: 'mdi:playlist-music'
        attribute_templates:
          jay_listening_url: "{{ state_attr('sensor.discord_englishmobster_2190', 'listening_url') }}"
          jay_listening_details: "{{ state_attr('sensor.discord_englishmobster_2190', 'listening_details') }}"
          jay_spotify_artist: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_artist') }}"
          jay_spotify_title: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_title') }}"
          jay_spotify_album: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_album') }}"
          jay_spotify_track_id: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_track_id') }}"
          jay_spotify_duration: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_duration') }}"
          jay_spotify_start:  "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_start') }}"
          jay_spotify_end: "{{ state_attr('sensor.discord_englishmobster_2190', 'spotify_end') }}"
      jay_watching:
        value_template: "{{ state_attr('sensor.discord_englishmobster_2190', 'watching') }}"
        friendly_name: "Jay Watching"
        icon_template: 'mdi:television-classic'
        attribute_templates:
          jay_watching_url: "{{ state_attr('sensor.discord_englishmobster_2190', 'watching_url') }}"
          jay_watching_details: "{{ state_attr('sensor.discord_englishmobster_2190', 'watching_details') }}"
      jay_custom_status:
        friendly_name: "Jay Discord Status"
        value_template: "{{ state_attr('sensor.discord_englishmobster_2190', 'custom_status') }}"
        icon_template: 'mdi:discord'
      air_quality:
        friendly_name: "Air Quality"
        value_template: >-
          {% if states('sensor.waqi_glendora_laurel_los_angeles')|int < 51 %}
            Good
          {% elif states('sensor.waqi_glendora_laurel_los_angeles')|int < 101 %}
            Moderate
          {% elif states('sensor.waqi_glendora_laurel_los_angeles')|int < 151 %}
            Somewhat Unhealthy
          {% elif states('sensor.waqi_glendora_laurel_los_angeles')|int < 201 %}
            Unhealthy
          {% elif states('sensor.waqi_glendora_laurel_los_angeles')|int < 301 %}
            Very Unhealthy
          {% else %}
            Hazardous
          {% endif %}
  - platform: derivative
    source: sensor.outside_temperature
    round: 1 
    unit_time: h
    time_window: "01:00:00"
  - platform: min_max
    name: Average temperature
    type: mean
    entity_ids:
      - sensor.bedroom_temperature
      - sensor.family_room_temperature
      - sensor.office_temperature
  - platform: waze_travel_time
    name: Travel Time Jay Work to Home
    origin: zone.jay_work
    destination: zone.home
    region: 'US'
    excl_filter: 'HOV'
    avoid_toll_roads: true
    avoid_subscription_roads: true
    avoid_ferries: true
  - platform: waze_travel_time
    name: Travel Time Home to Jay Work
    origin: zone.home
    destination: zone.jay_work
    region: 'US'
    excl_filter: 'HOV'
    avoid_toll_roads: true
    avoid_subscription_roads: true
    avoid_ferries: true
  - platform: derivative
    source: sensor.travel_time_home_to_jay_work
    round: 1 
    unit_time: h
    time_window: "00:15:00"
  - platform: derivative
    source: sensor.travel_time_jay_work_to_home
    round: 1 
    unit_time: h
    time_window: "00:15:00"
  - platform: mqtt
    name: "Plex Playing"
    state_topic: "plex/update"
    value_template: '{{ value_json.event == "media.resume" or value_json.event == "media.play" }}'
    force_update: true
    json_attributes_topic: "plex/update/attributes"
  - platform: deluge
    host: !secret nas_server_ip
    username: !secret deluge_username
    password: !secret deluge_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
  - platform: version
  - platform: season
    type: meteorological
    name: Meteorological Season
  - platform: season
    type: astronomical
    name: Astronomical Season
  - platform: youtube
    channel_id: UC2gB7YCgfHIskI3HsY1teDw
  - platform: youtube
    channel_id: UCBODyKF0JMbUd6D9Bklyzbw
  - platform: youtube
    channel_id: UCL7DDQWP6x7wy0O6L5ZIgxg
  - platform: youtube
    channel_id: UCVo63lbKHjC04KqYhwSZ_Pg
  - platform: youtube
    channel_id: UCpIafFPGutTAKOBHMtGen7g
  - platform: youtube
    channel_id: UCmOy2-vrvwDh6O1bTUB5m_g
  - platform: discord_game
    token: !secret discord_bot_token
    image_format: png
    members:
      - EnglishMobster#2190
