#tesla:
# username: !secret tesla_username
# password: !secret tesla_password

sensor:
  - platform: derivative
    source: sensor.euphrates_eevee_temperature_sensor_inside
    round: 1 
    unit_time: h
    time_window: "00:30:00"