alias: Plex Webhook
initial_state: 'on'
trigger:
  platform: webhook
  webhook_id: !secret plex_webhook
action:
- service: mqtt.publish
  data_template:
    topic: 'plex/update'
    payload_template: >
      {{ (trigger.data['payload'] | string)[12:][:-2] | replace ("\\\\", "\\") | replace ("\\\'", "'") | replace ("\\x","?") }}