alias: Plex Parse
initial_state: 'on'
trigger:
  platform: mqtt
  topic: 'plex/update'
condition:
  condition: and
  conditions:
    - condition: template        
      value_template: "{{trigger.payload_json.event != 'media.scrobble'}}"          
    - condition: template
      value_template: "{{trigger.payload_json.event != 'media.rate'}}"                    
action:
  - service: mqtt.publish
    data_template:
      topic: 'plex/update/attributes'
      retain: true
      payload_template: >
       {  "Event":"{{ trigger.payload_json.event }}", 
          "Account":"{{ trigger.payload_json.Account.title }}", 
          "Title":"{{ trigger.payload_json.Metadata.title }}", 
          "Type":"{{ trigger.payload_json.Metadata.librarySectionType }}" }